CREATE SCHEMA IF NOT EXISTS iot_data;

CREATE TABLE IF NOT EXISTS iot_data.F_SENSOR_DATA_DISTRIBUTED (
    H_SENSOR_KEY VARCHAR,
    H_MEASUREMENT_KEY VARCHAR,
    TIMESTAMP TIMESTAMP,
    DISTANCE DOUBLE,
    VALUE DOUBLE,
    LOAD_DATE DATE,
    RECORD_SOURCE VARCHAR
)
WITH (
    format = 'PARQUET',
    partitioning = ARRAY['LOAD_DATE']
);